In [51]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.0


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [52]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [53]:
scalar.ndim

0

In [54]:
# Get tensor back as Python int
scalar.item()

7

In [55]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([2])

In [58]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [59]:
MATRIX.ndim

2

In [60]:
MATRIX[1]

tensor([ 9, 10])

In [61]:
MATRIX.shape

torch.Size([2, 2])

In [62]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [63]:
TENSOR.ndim

3

In [64]:
TENSOR.shape

torch.Size([1, 3, 3])

In [65]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [66]:
print(TENSOR[0])
print("")
print(TENSOR[0][1])
print(TENSOR[0][1][0])
print(TENSOR[0][1][1])
print(TENSOR[0][1][2])


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

tensor([3, 6, 9])
tensor(3)
tensor(6)
tensor(9)


### Random tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [67]:
# Create a random tensors of size/shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4044, 0.0853, 0.9487, 0.4651],
        [0.4323, 0.4337, 0.2146, 0.6999],
        [0.8246, 0.2957, 0.6955, 0.5025]])

In [68]:
# Create a random tesor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [69]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
ones.dtype

torch.float32

In [72]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [73]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
torch.__version__

'1.12.0'

In [75]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [76]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_32_tensor.dtype


torch.float32

In [78]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [79]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [80]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor


tensor([3, 6, 9])

In [81]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [82]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.5587, 0.3575, 0.0532, 0.5232],
        [0.3073, 0.9702, 0.9970, 0.6999],
        [0.9530, 0.4659, 0.1999, 0.7416]])

In [83]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.5587, 0.3575, 0.0532, 0.5232],
        [0.3073, 0.9702, 0.9970, 0.6999],
        [0.9530, 0.4659, 0.1999, 0.7416]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [84]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [85]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [86]:
tensor


tensor([1, 2, 3])

In [87]:
# Substract 10
tensor - 10


tensor([-9, -8, -7])

In [88]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [89]:
torch.add(tensor, 10)


tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [90]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.9570, 2.0143, 2.5691],
        [2.5872, 2.0316, 2.5430],
        [2.8871, 2.3107, 2.6141]])

In [91]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [92]:
# Matrix multiplication
print(torch.matmul(tensor, tensor))
# Alternative
print(torch.sum(torch.mul(tensor, tensor)))
# Alternative 2
print(torch.sum(tensor*tensor))


tensor(14)
tensor(14)
tensor(14)


In [93]:
tensor


tensor([1, 2, 3])

In [94]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3


14

In [95]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: total: 0 ns
Wall time: 500 µs


In [96]:
%%time
torch.matmul(tensor, tensor)


CPU times: total: 0 ns
Wall time: 500 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [97]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
                         
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape


(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape


(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)


In [99]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype


(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [100]:
# Find the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [101]:
# Find the max
torch.max(x), x.max()


(tensor(91), tensor(91))

In [102]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [103]:
# Find the sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

## Finding the positional min and max


In [105]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [106]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmin()


tensor(0)

In [107]:
x[0]


tensor(1)

In [108]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()


tensor(9)

In [109]:
x[9]


tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [139]:
import torch

def create_x(number_1, number_2):
    # Let's create a tensor
    nr = torch.arange(number_1, number_2)
    print(nr, nr.shape)
    return nr

def reshape(_numbers, number_1, number_2):
    # Add an extra dimension
    x_reshaped = _numbers.reshape(number_1, number_2)
    print(x_reshaped, x_reshaped.shape)


In [163]:
x = create_x(1., 10.)
print("")
reshape(x, 9, 1)
print("")
reshape(x, 1, 9)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [164]:
x2 = create_x(1., 13.)
print("")
reshape(x2, 3, 4)
print("")
reshape(x2, 6, 2)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) torch.Size([3, 4])

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])


In [149]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [150]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [158]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [162]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [165]:
x_reshaped = x.reshape(1, 9)
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [166]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [167]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [172]:
x_original


tensor([[[0.8665, 0.5589, 0.5156],
         [0.8462, 0.4264, 0.3698],
         [0.4018, 0.2852, 0.6874],
         ...,
         [0.5563, 0.2938, 0.6024],
         [0.9649, 0.3874, 0.0541],
         [0.1135, 0.5866, 0.7874]],

        [[0.4328, 0.0984, 0.5631],
         [0.5520, 0.0843, 0.9381],
         [0.1988, 0.9131, 0.0902],
         ...,
         [0.2713, 0.8602, 0.9296],
         [0.5518, 0.8738, 0.7159],
         [0.6112, 0.5767, 0.3534]],

        [[0.6088, 0.1209, 0.4547],
         [0.7834, 0.6594, 0.1554],
         [0.9922, 0.1339, 0.9449],
         ...,
         [0.0881, 0.9661, 0.1678],
         [0.4079, 0.5040, 0.8595],
         [0.9118, 0.8279, 0.1836]],

        ...,

        [[0.9458, 0.9583, 0.6248],
         [0.7516, 0.5818, 0.2131],
         [0.0623, 0.2402, 0.9450],
         ...,
         [0.7144, 0.5286, 0.3607],
         [0.5480, 0.4707, 0.1856],
         [0.1984, 0.3191, 0.1471]],

        [[0.3082, 0.1384, 0.7064],
         [0.1522, 0.4055, 0.4861],
         [0.

In [173]:
x_permuted


tensor([[[0.8665, 0.8462, 0.4018,  ..., 0.5563, 0.9649, 0.1135],
         [0.4328, 0.5520, 0.1988,  ..., 0.2713, 0.5518, 0.6112],
         [0.6088, 0.7834, 0.9922,  ..., 0.0881, 0.4079, 0.9118],
         ...,
         [0.9458, 0.7516, 0.0623,  ..., 0.7144, 0.5480, 0.1984],
         [0.3082, 0.1522, 0.9733,  ..., 0.1304, 0.2158, 0.1941],
         [0.5167, 0.5507, 0.9274,  ..., 0.9466, 0.9136, 0.4691]],

        [[0.5589, 0.4264, 0.2852,  ..., 0.2938, 0.3874, 0.5866],
         [0.0984, 0.0843, 0.9131,  ..., 0.8602, 0.8738, 0.5767],
         [0.1209, 0.6594, 0.1339,  ..., 0.9661, 0.5040, 0.8279],
         ...,
         [0.9583, 0.5818, 0.2402,  ..., 0.5286, 0.4707, 0.3191],
         [0.1384, 0.4055, 0.3748,  ..., 0.8595, 0.9818, 0.4544],
         [0.6322, 0.6642, 0.3920,  ..., 0.3200, 0.1921, 0.6575]],

        [[0.5156, 0.3698, 0.6874,  ..., 0.6024, 0.0541, 0.7874],
         [0.5631, 0.9381, 0.0902,  ..., 0.9296, 0.7159, 0.3534],
         [0.4547, 0.1554, 0.9449,  ..., 0.1678, 0.8595, 0.

In [174]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(728218.), tensor(728218.))

In [177]:
x_original[0, 0, 0], x_original[0, 0, 1], x_original[0, 0, 2]


(tensor(728218.), tensor(0.5589), tensor(0.5156))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [179]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [180]:
# Let's index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [181]:
# Let's index on the middle bracket (dim=1)
x[0][0]


tensor([1, 2, 3])

In [182]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]


tensor(5)

In [184]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]


tensor([[1, 2, 3]])

In [185]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]


tensor([[2, 5, 8]])

In [186]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [187]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]


tensor([1, 2, 3])

In [188]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])


tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library. 

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()` 

In [190]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [191]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [192]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [193]:
# Change the tesnor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [195]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.7594, 0.9169, 0.5529, 0.1315],
        [0.8445, 0.7005, 0.3517, 0.9775],
        [0.9710, 0.3596, 0.5829, 0.9279]])
tensor([[0.5636, 0.9094, 0.9582, 0.4501],
        [0.7282, 0.6716, 0.4414, 0.4706],
        [0.0763, 0.4981, 0.2262, 0.8978]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [196]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
